server:
  port: 8081
  url: http://localhost

spring:
  datasource:
    url: jdbc:mysql://gathering.cvuk42kqur71.ap-northeast-2.rds.amazonaws.com:3306/payment
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

jwt:
  secretKey: scretkeyscretkey
  access:
    expiration: 3600
  refresh:
    expiration: 3600

redis:
  host: 43.201.58.29
  port: 6379

toss:
  widget:
    secretKey: zzzz
  server:
    url: ${TOSS_SERVER_URL:https://api.tosspayments.com/v1/payments/confirm}
  cancel:
    url: ${TOSS_CANCEL_URL:https://api.tosspayments.com/v1/payments/%s/cancel}

logging:
  level:
    org.hibernate.SQL: debug
payment:
  api:
    url: aa
    secretKey: aa